# Generated by Django 5.1.2 on 2024-10-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientesjahr', '0001_initial'),
    ]

    operations = [
    ]
